dist: xenial
language: python
python:
  - '3.6'
install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -n test-environment -f env.yml
  - source activate test-environment
  - pyinstaller main.py -n r2d2 --onefile
script:
  - echo "skipping tests"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: n6F4E+/PQF5/tYnQ4QhRHVbV8C758AgoGG5SUL0QfjlyUSWrNcZwXabyV4UzgkROIIFTxx3GpQELVb5gu0QxJdIShyRI3SbWkAlqTIE6K9Y8RoIRGMXQ8Z7AoxSUqeu+ZIcuUrUzCTwYs+ZJARs0WPUF7KeteMdGPuvZDUg0IU6aA9hwZjFiG4J0geC+XULtdqmgPeO5mNXWd7xk7W831APOmVWBFl/rLnyhwcJobKoKgGIb5Na6yiPcsfezSlQ3oq6pEVQ5jeSN8u16ltJ+KRZazKrwjqOf4johpesHaBBeZoruwHns1AFgOWPicTNMk9k6dzmwjbR9eEZSfnojkMdRf8FJ8DjxtdGgZuzg+vunFPcYlE1m968Fqig0ZUNee5vMD09Spnz17ozaY+bMAZwAqBbYhmSjKWj9Kl/UUsUxYZQDlHUMTbOm9gw0JfeP0qHzBGCY9mAuTKbd6Q5Stxgmp92jrxnjl2+Smq7sbv6BrZQD4khHDAUkOEqlghma8uPRQ2Crsl80S9Wl52Z2Vh5ZoCr3bZqbm4GcVyTROrZdM78szlU1Ls/5de2+oGgzeAj7jyr9/zCmrHJIrx7jK3eb2tMpfl+eWKFVvojuR9bbwS14q9sz1Dthu8l3zjUj65yh/U954hCl1YBhe3HUCzTHXjrraFKgLeiGv67Sedk=
  file: dist/r2d2
  on:
    repo: ArcCha/r2d2
    tags: true
    branch: master
